Solution for 4-2
js-tasks-ru/vue-20200615_kivals-90 pull request #10
Opened 2020-08-19 09:09 UTC by kivals

2020-08-19 09:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
AppCheckbox
+ AppCheckbox должен рендерить слот
- AppCheckbox должен обрабатывать нативные события (focus)
- AppCheckbox должен пробрасывать атрибуты на input
- AppCheckbox должен отображать состояние, соответствующее логическому checked
- AppCheckbox должен отображать состояние в соответствии со списком в checked
- AppCheckbox должен порождать событие change с новым значением bool checked при изменении значения checkbox
- AppCheckbox должен порождать событие change с массивом значений выбранных значений при изменении значения checkbox
```
```diff
ScrollBehavior
+ По умолчанию страница прокручивается вверх
+ При переходе назад с savedPosition не изменяется положение прокрутки
+ При наличии hash в маршруте прокручивается к нему
+ Если переход происходит между маршрутами, содержащими в пути истинное meta свойство saveScrollPosition, положение прокрутки не должно меняться
+ Если переход происходит между маршрутами, где только один содержит saveScrollPosition, остаётся поведение по умолчанию
```

2020-08-20 14:19 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
AppCheckbox
+ AppCheckbox должен рендерить слот
+ AppCheckbox должен обрабатывать нативные события (focus)
+ AppCheckbox должен пробрасывать атрибуты на input
+ AppCheckbox должен отображать состояние, соответствующее логическому checked
+ AppCheckbox должен отображать состояние в соответствии со списком в checked
+ AppCheckbox должен порождать событие change с новым значением bool checked при изменении значения checkbox
+ AppCheckbox должен порождать событие change �� массивом значений выбранных значений при изменении значения checkbox
```
```diff
ScrollBehavior
+ По умолчанию страница прокручивается вверх
+ При переходе назад с savedPosition не изменяется положение прокрутки
+ При наличии hash в маршруте прокручивается к нему
+ Если переход происходит между маршрутами, содержащими в пути истинное meta свойство saveScrollPosition, положение прокрутки не должно меняться
+ Если переход происходит между маршрутами, где только один содержит saveScrollPosition, остаётся поведение по умолчанию
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-08-20 14:33 UTC, ShGKme requested changes
Задача 4-2 принята 👍

А вот задача 8-1 не работает (хотя проходит тесты).
То, что она не работает, можно увидеть на странице http://localhost:8080/8-module-1-task

Ваше решение:
![wrong](https://user-images.githubusercontent.com/25978914/90785604-f0b16080-e31b-11ea-9b10-fbdc921e5d1d.gif)

Ожидаемое поведение:
![right](https://user-images.githubusercontent.com/25978914/90785634-fb6bf580-e31b-11ea-9440-939676875e93.gif)

2020-08-20 14:33 UTC, ShGKme commented on 8-module/1-task/components/AppCheckbox.vue
> +    },
Это правильный код

2020-08-21 07:30 UTC, kivals commented on 8-module/1-task/components/AppCheckbox.vue
> +    },
В коммитах запутался, извиняюсь. 
Это свойство я подсмотрел, но так и не понял зачем мы `delete listeners.change` ? Можете вкратце пояснить?

2020-08-21 07:33 UTC, jsru commented
@ShGKme ping :)

2020-08-21 10:17 UTC, ShGKme commented on 8-module/1-task/components/AppCheckbox.vue
> +    },
@kivals, когда мы устанавливаем `v-on="$listeners"`, то мы проксируем нативное событие `change` у инпута, которому приходит нативый объект `Event`. Но снаружи у нас тоже модель `checked + change`. И ожидаем мы в `checked` получить не `Event`, а значение (`Boolean` или `Array`).

Тот `emit('change')`, который мы делаем в сеттере, не перекрывает проксированный, так как через `v-on="$listeners"` мы явно указали, кто именно обрабатывает событие `change`.

2020-08-21 10:17 UTC, ShGKme commented on 8-module/1-task/components/AppCheckbox.vue
> +    },
Чтобы этой проблемы не было, мы просто убираем `change` из `listeners`, и управляем им сами

2020-08-21 10:19 UTC, ShGKme approved these changes
Принято! 👍
Но есть лишняя строчка)

2020-08-21 10:19 UTC, ShGKme commented on 8-module/1-task/components/AppCheckbox.vue
> +      :checked="checked"
Так как `v-model = checked + change`, то `checked` отдельно передавать уже не нужно. Он корректно будет работать из геттера в модели. Это ни на что не влияет, но лишняя строчка

2020-08-21 10:19 UTC, merged

2020-08-21 11:32 UTC, kivals commented on 8-module/1-task/components/AppCheckbox.vue
> +    },
разобрался. спасибо